name: Get Latest Boomi Versions

on:
  workflow_dispatch:

jobs:
  extract-latest-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install pandas

      - name: Compute latest Boomi versions
        run: |
          python3 <<EOF
          import pandas as pd
          import json

          # Load CSV
          df = pd.read_csv('readyForCodeReview.csv', header=None, names=['modifiedBy', 'componentId'])

          # Load JSON metadata
          with open('boomi-metadata/components_modified_20250530_040646.json') as f:
              metadata = json.load(f)['result']

          # Convert to DataFrame
          meta_df = pd.DataFrame(metadata)

          # Prepare results
          results = []
          for _, row in df.iterrows():
              user = row['modifiedBy']
              component_id = row['componentId']
              matches = meta_df[(meta_df['modifiedBy'] == user) & (meta_df['componentId'] == component_id)]
              if not matches.empty:
                  latest = matches.sort_values('version', ascending=False).iloc[0]
                  results.append([user, component_id, latest['version']])

          # Output CSV
          output_df = pd.DataFrame(results, columns=['modifiedBy', 'componentId', 'latestVersion'])
          output_df.to_csv('boomi-latest-versions.csv', index=False)
          EOF

      - name: Commit results
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add boomi-latest-versions.csv
          git commit -m "Add Boomi latest version results" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
