name: Get Latest Component Versions

on:
  workflow_dispatch:

jobs:
  extract-latest-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run Python script to compute latest component versions
        run: |
          python <<EOF
          import json
          import csv
          import glob

          # Load CSV with modified_by and component_id
          with open('readyForCodeReview.csv') as f:
              reader = csv.reader(f)
              review_data = list(reader)

          # Find the latest JSON metadata file (e.g., components_modified_*.json)
          json_files = glob.glob('boomi-metadata/components_modified_*.json')
          if not json_files:
              raise FileNotFoundError("No component metadata JSON file found.")
          latest_json = max(json_files, key=lambda x: x.split('_')[-1].split('.')[0])

          # Load JSON file
          with open(latest_json) as f:
              deployments = json.load(f)

          # Build result list
          result = []
          for row in review_data:
              modified_by, component_id = row
              versions = [
                  int(entry["version"])
                  for entry in deployments
                  if entry["id"] == component_id and entry["modifiedBy"] == modified_by
              ]
              latest_version = max(versions) if versions else "N/A"
              result.append([modified_by, component_id, latest_version])

          # Write new CSV
          with open('review_ready_with_versions.csv', 'w', newline='') as f:
              writer = csv.writer(f)
              writer.writerow(["modified_by", "component_id", "latest_version"])
              writer.writerows(result)
          EOF

      - name: Commit result CSV to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add review_ready_with_versions.csv
          git commit -m "Add review_ready_with_versions.csv with latest version info" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
